<?php
$_helper = $this->helper('catalog/output');
$coreString = Mage::Helper('core/string');
$checkoutHelper = Mage::helper('checkout');
?>
<?php if (!$this->getLoadedProductCollection()->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
        <div class="page-title">
            <h2><?php echo $this->__("%d product(s) were found for '%s'", $this->getProductCollectionByBrand()->getSize(), $this->getBrand()->getTitle()); ?></h2>
        </div>
    <?php echo $this->getToolbarHtml() ?>
    <?php echo $this->getAdditionalHtml() ?>
	<h3 class="listing-subtile"><?php echo $this->__('Wines')?></h3>
    <div class="category-products">
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($this->getProductCollectionByBrand() as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($this->getProductCollectionByBrand())): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 160); ?>" width="150" height="160" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(),'name'); ?></a></h2>
                                <div class="list-content">    
                                    <?php if ($wine_type = $_product->getResource()->getAttribute('wine_type')->getFrontend()->getValue($_product)): ?>
                                        <?php if ($wine_type != "No"): ?>
                                            <span class="attribute-list"><b><?php echo $this->__('TYPE')?></b><?php echo str_replace("Wine", "", $wine_type); ?></span>
                                        <?php endif;?>
                                    <?php endif; ?>
                                    <?php if ($wine_country = $_product->getResource()->getAttribute('wine_country')->getFrontend()->getValue($_product)): ?>
                                        <?php if ($wine_country != "No"): ?>
                                            <span class="attribute-list"><b><?php echo $this->__('COUNTRY')?></b><?php echo $wine_country; ?></span>
                                        <?php endif;?>
                                    <?php endif; ?>

                                    <span class="attribute-list">  
                                        <?php if (($wine_region2 = $_product->getResource()->getAttribute('wine_region2')->getFrontend()->getValue($_product))) : ?>    
                                            <?php if ($wine_region2 != "No"): ?>
                                                <b><?php echo $this->__('Region2')?></b><?php echo $wine_region2; ?>
                                            <?php endif;?>    
                                        <?php endif; ?>
                                        <?php if (($wine_region = $_product->getResource()->getAttribute('wine_region')->getFrontend()->getValue($_product))) : ?>    
                                            <?php if ($wine_region2 != "No"): ?>
                                                <?php echo " - "; ?>
                                            <?php endif; ?>
                                            <?php if ($wine_region != "No"): ?>
                                                <b><?php echo $this->__('Region')?></b><?php echo $wine_region; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </span>                
                                    <?php $vintage = $_product->getVintage();
                                    if (!empty($vintage) && $vintage != "NV"): ?>
                                        <span class="attribute-list"><b><?php echo $this->__('YEAR')?></b><?php echo $vintage; ?></span>
                                    <?php endif; ?>    
                                    <?php if($rating_wsa = $_product->getResource()->getAttribute('rating_wsa')->getFrontend()->getValue($_product)): ?>
                                        <?php if ($rating_wsa != "No"): ?>
                                        <span class="wsa"><span class="label"><?php echo $this->__('WSA'); ?></span><span><?php echo $rating_wsa; ?></span></span>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="list-content">
                                    <?php if ($_product->getPrice() > $_product->getFinalPrice()): ?>
                                        <ul>
                                            <li>
                                                <label><?php echo $this->__('Price') ?>:</label>
                                                <span class="old-price"><span class="price"><?php 
                                                    echo $checkoutHelper->formatPrice($_product->getPrice());
                                                    ?></span>
                                                </span>
                                                <span class="new-price"><?php 
                                                    echo $checkoutHelper->formatPrice($_product->getFinalPrice());
                                                    ?></span>
                                            </li>
                                            <?php
                                            $savePrice = $_product->getPrice() - $_product->getFinalPrice();
                                            $saveParcentage = 100 * $savePrice / $_product->getPrice();
                                            ?>      
                                            <li>
                                                <label><?php echo $this->__('Save') ?>:</label>
                                                <span class="saved-price"><?php 
                                                echo $checkoutHelper->formatPrice($savePrice);
                                                ?> (<?php 
                                                echo $checkoutHelper->formatPrice($saveParcentage);
                                                ?>%)</span>
                                            </li>
                                        </ul>
                                    <?php else : ?>
                                        <ul class="catalog-price-list">
                                            <li>
                                                <label><?php echo $this->__('Price') ?>:</label>
                                                <span class="price"><?php 
                                                echo $checkoutHelper->formatPrice($_product->getPrice()); 
                                                ?></span>
                                            </li>
                                        </ul>
                                    <?php endif; ?>
                                    <div class="bottle"><label>Bottle(s)</label><input type="text" name="qty<?php echo $_product->getId(); ?>" id="qty<?php echo $_product->getId(); ?>" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" /></div>

                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button button22 notebutton" onclick="ajaxAddToCart( this, '<?php echo $_product->getId() ?>',jQuery('#qty<?php echo $_product->getId(); ?>').val())"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li>
                                                <a href="javascript:void(0);" onclick="ajaxAddToWishlist('<?php echo $_product->getId(); ?>',jQuery('#qty<?php echo $_product->getId(); ?>').val())" class="link-wishlist notebutton"><?php echo $this->__('Add to Wishlist') ?></a>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                                <div class="list-content">
                                    <div class="desc std">
                                        <?php echo $coreString->truncate($_product->getShortDescription(), 170, ''); ?>    
                                        <br/>
                                        <a class="learn-more" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $this->__('Learn More') ?></a>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
        <?php else: ?>
            <?php // Grid Mode  ?>
            <?php $_collectionSize = $this->getProductCollectionByBrand()->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php
            $i = 0;
            foreach ($this->getProductCollectionByBrand() as $_product):
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid">
                    <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="actions">
                            <?php if ($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>
    </div>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
        <?php echo $this->getAdditionalHtml() ?>
    </div>
<?php endif; ?>